export const Posts = [
    {
        id: 1,
        desc: "Love all my friends",
        photo: "/assets/Post/Post1.jpg",
        date: "5 phút",
        userId: 1,
        like: 32,
        comment: 30,
        share: 9,
    },
    {
        id: 2,
        desc: "Chilling on the beach",
        photo: "/assets/Post/Post2.jpg",
        date: "10 phút",
        userId: 2,
        like: 25,
        comment: 18,
        share: 5,
    },
    {
        id: 3,
        desc: "Coffee time ☕",
        photo: "/assets/Post/Post3.jpg",
        date: "15 phút",
        userId: 3,
        like: 41,
        comment: 20,
        share: 7,
    },
    {
        id: 4,
        desc: "My new shoes 👟",
        photo: "/assets/Post/Post4.jpg",
        date: "20 phút",
        userId: 4,
        like: 12,
        comment: 6,
        share: 2,
    },
    {
        id: 5,
        desc: "Good vibes only ✨",
        photo: "/assets/Post/Post5.jpg",
        date: "25 phút",
        userId: 5,
        like: 55,
        comment: 33,
        share: 11,
    },
    {
        id: 6,
        desc: "Workout done 💪",
        photo: "/assets/Post/Post6.jpg",
        date: "30 phút",
        userId: 6,
        like: 19,
        comment: 9,
        share: 3,
    },
    {
        id: 7,
        desc: "Nature walk 🌳",
        photo: "/assets/Post/Post7.jpg",
        date: "35 phút",
        userId: 7,
        like: 47,
        comment: 28,
        share: 14,
    },
    {
        id: 8,
        desc: "Happy weekend 🥳",
        photo: "/assets/Post/Post8.jpg",
        date: "40 phút",
        userId: 8,
        like: 22,
        comment: 11,
        share: 4,
    },
    {
        id: 9,
        desc: "Delicious dinner 🍽️",
        photo: "/assets/Post/Post9.jpg",
        date: "45 phút",
        userId: 9,
        like: 36,
        comment: 16,
        share: 6,
    },
    {
        id: 10,
        desc: "Road trip 🚗",
        photo: "/assets/Post/Post10.jpg",
        date: "50 phút",
        userId: 10,
        like: 28,
        comment: 12,
        share: 5,
    },
];

export const Users = [
  {
    id: 1,
    fullname: "Anna",
    profilePicture: "/assets/Person/Person1.jpg",
    email: 'Anna@gmail.com',
    password: '123456',
    friends: [2, 3, 5, 7],
    desc: "Thích du lịch và chụp ảnh.",
  },
  {
    id: 2,
    fullname: "John",
    profilePicture: "/assets/Person/Person2.jpg",
    email: 'John@gmail.com',
    password: '123456',
    friends: [1, 4],
    desc: "Lập trình viên đam mê công nghệ.",
  },
  {
    id: 3,
    fullname: "Sarah",
    profilePicture: "/assets/Person/Person3.jpg",
    email: 'Sarah@gmail.com',
    password: '123456',
    friends: [1, 6],
    desc: "Yêu thích đọc sách và viết lách.",
  },
  {
    id: 4,
    fullname: "Michael",
    profilePicture: "/assets/Person/Person1.jpg",
    email: 'Michael@gmail.com',
    password: '123456',
    friends: [2],
    desc: "Người chơi bóng rổ chuyên nghiệp.",
  },
  {
    id: 5,
    fullname: "Emily",
    profilePicture: "/assets/Person/Person2.jpg",
    email: 'Emily@gmail.com',
    password: '123456',
    friends: [1, 7, 9],
    desc: "Yêu động vật và thiên nhiên.",
  },
  {
    id: 6,
    fullname: "David",
    profilePicture: "/assets/Person/Person3.jpg",
    email: 'David@gmail.com',
    password: '123456',
    friends: [3, 8],
    desc: "Thích chơi game và khám phá công nghệ mới.",
  },
  {
    id: 7,
    fullname: "Sophia",
    profilePicture: "/assets/Person/Person1.jpg",
    email: 'Sophia@gmail.com',
    password: '123456',
    friends: [5, 1],
    desc: "Đam mê thời trang và thiết kế.",
  },
  {
    id: 8,
    fullname: "Daniel",
    profilePicture: "/assets/Person/Person2.jpg",
    email: 'Daniel@gmail.com',
    password: '123456',
    friends: [6, 9, 10],
    desc: "Người thích tập gym và thể thao.",
  },
  {
    id: 9,
    fullname: "Olivia",
    profilePicture: "/assets/Person/Person3.jpg",
    email: 'Olivia@gmail.com',
    password: '123456',
    friends: [5, 8],
    desc: "Yêu thích nấu ăn và du lịch.",
  },
  {
    id: 10,
    fullname: "James",
    profilePicture: "/assets/Person/Person1.jpg",
    email: 'James@gmail.com',
    password: '123456',
    friends: [8],
    desc: "Thích âm nhạc và chơi guitar.",
  },
  {
    id: 11,
    fullname: "Messi",
    profilePicture: "/assets/Person/Person1.jpg",
    email: 'Messi@gmail.com',
    password: '123456',
    friends: [8],
    desc: "Thích âm nhạc và chơi guitar.",
  },
];

export const Messages = [
  {
    id: 1,
    idSend: 1,
    idReceive: 2,
    text: "Chào John, bạn khỏe không?",
  },
  {
    id: 2,
    idSend: 2,
    idReceive: 1,
    text: "Mình khỏe, cảm ơn Anna! Còn bạn?",
  },
  {
    id: 3,
    idSend: 3,
    idReceive: 6,
    text: "David, hôm nay bạn có chơi game không?",
  },
  {
    id: 4,
    idSend: 6,
    idReceive: 3,
    text: "Có chứ, Sarah! Bạn muốn tham gia không?",
  },
  {
    id: 5,
    idSend: 5,
    idReceive: 9,
    text: "Olivia, cuối tuần này đi du lịch nhé?",
  },
  {
    id: 6,
    idSend: 9,
    idReceive: 5,
    text: "Tuyệt vời, Emily! Mình sẵn sàng.",
  },
  {
    id: 7,
    idSend: 8,
    idReceive: 10,
    text: "James, tối nay tập gym cùng nhau không?",
  },
  {
    id: 8,
    idSend: 10,
    idReceive: 8,
    text: "Được thôi, Daniel! Gặp lúc 7h tối nhé.",
  },
];