export const Posts = [
    {
        id: 1,
        desc: "Love all my friends",
        photo: "/assets/Post/Post1.jpg",
        date: "5 min ago",
        userId: 1,
        like: 32,
        comment: 30,
        share: 9,
    },
    {
        id: 2,
        desc: "Chilling on the beach",
        photo: "/assets/Post/Post2.jpg",
        date: "10 min ago",
        userId: 2,
        like: 25,
        comment: 18,
        share: 5,
    },
    {
        id: 3,
        desc: "Coffee time ☕",
        photo: "/assets/Post/Post3.jpg",
        date: "15 min ago",
        userId: 3,
        like: 41,
        comment: 20,
        share: 7,
    },
    {
        id: 4,
        desc: "My new shoes 👟",
        photo: "/assets/Post/Post4.jpg",
        date: "20 min ago",
        userId: 4,
        like: 12,
        comment: 6,
        share: 2,
    },
    {
        id: 5,
        desc: "Good vibes only ✨",
        photo: "/assets/Post/Post5.jpg",
        date: "25 min ago",
        userId: 5,
        like: 55,
        comment: 33,
        share: 11,
    },
    {
        id: 6,
        desc: "Workout done 💪",
        photo: "/assets/Post/Post6.jpg",
        date: "30 min ago",
        userId: 6,
        like: 19,
        comment: 9,
        share: 3,
    },
    {
        id: 7,
        desc: "Nature walk 🌳",
        photo: "/assets/Post/Post7.jpg",
        date: "35 min ago",
        userId: 7,
        like: 47,
        comment: 28,
        share: 14,
    },
    {
        id: 8,
        desc: "Happy weekend 🥳",
        photo: "/assets/Post/Post8.jpg",
        date: "40 min ago",
        userId: 8,
        like: 22,
        comment: 11,
        share: 4,
    },
    {
        id: 9,
        desc: "Delicious dinner 🍽️",
        photo: "/assets/Post/Post9.jpg",
        date: "45 min ago",
        userId: 9,
        like: 36,
        comment: 16,
        share: 6,
    },
    {
        id: 10,
        desc: "Road trip 🚗",
        photo: "/assets/Post/Post10.jpg",
        date: "50 min ago",
        userId: 10,
        like: 28,
        comment: 12,
        share: 5,
    },
];

export const Users = [
  {
    id: 1,
    username: "Anna",
    profilePicture: "/assets/Person/Person1.jpg",
    email: 'Anna@gmail.com',
    password: '123456',
    friends: [],
  },
  {
    id: 2,
    username: "John",
    profilePicture: "/assets/Person/Person2.jpg",
    email: 'John@gmail.com',
    password: '123456',
    friends: [1, 4],
  },
  {
    id: 3,
    username: "Sarah",
    profilePicture: "/assets/Person/Person3.jpg",
    email: 'Sarah@gmail.com',
    password: '123456',
    friends: [1, 6],
  },
  {
    id: 4,
    username: "Michael",
    profilePicture: "/assets/Person/Person1.jpg",
    email: 'Michael@gmail.com',
    password: '123456',
    friends: [2],
  },
  {
    id: 5,
    username: "Emily",
    profilePicture: "/assets/Person/Person2.jpg",
    email: 'Emily@gmail.com',
    password: '123456',
    friends: [1, 7, 9],
  },
  {
    id: 6,
    username: "David",
    profilePicture: "/assets/Person/Person3.jpg",
    email: 'David@gmail.com',
    password: '123456',
    friends: [3, 8],
  },
  {
    id: 7,
    username: "Sophia",
    profilePicture: "/assets/Person/Person1.jpg",
    email: 'Sophia@gmail.com',
    password: '123456',
    friends: [5],
  },
  {
    id: 8,
    username: "Daniel",
    profilePicture: "/assets/Person/Person2.jpg",
    email: 'Daniel@gmail.com',
    password: '123456',
    friends: [6, 9, 10],
  },
  {
    id: 9,
    username: "Olivia",
    profilePicture: "/assets/Person/Person3.jpg",
    email: 'Olivia@gmail.com',
    password: '123456',
    friends: [5, 8],
  },
  {
    id: 10,
    username: "James",
    profilePicture: "/assets/Person/Person1.jpg",
    email: 'James@gmail.com',
    password: '123456',
    friends: [8],
  },
];